accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"   


urlpatterns = [
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name= "logout"),
]

base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('about/', views.About.as_view(), name="about"),
    path('contact/', views.Contact.as_view(), name="contact"),
    path('faq/', views.Faq.as_view(), name="faq"),
    path('pricing/', views.Pricing.as_view(), name="pricing"),
    
]

cart/urls.py
  
from django.urls import path
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart

app_name= 'cart'

urlpatterns = [
    
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
]

products/urls.py
from django.urls import path
from . import views  

app_name = 'products'

urlpatterns = [
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'), 
    path('all/', views.ProductListView.as_view(), name='product_list'),
    path('create/product/<slug:slug>/', views.ProductCreateView.as_view(), name='create_product'),
    path('delete/product/<slug:slug>/', views.ProductDeleteView.as_view(), name='delete_product'),
    path('update/product/<slug:slug>/', views.ProductUpdateView.as_view(), name='update_product'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('timeline/<slug>/', views.UserDetailView.as_view(), name='user_detail'),
    path('all/', views.UserListView.as_view(), name='users'),
    path('update/profile/<slug>/', views.UserUpdateView.as_view(), name='user_update'),
    path('delete/profile/<slug>/', views.UserDeleteView.as_view(), name='user_delete'),
]

vstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/alerts.html
{% if messages %}

<div class="row" style="margin-top: 60px;">
    <div class="col-12">
        {% for message in messages %}
        <div {% if message.tags %} class="alert {{ message.tags }} alert-dismissible fade show" role="alert" {% endif %}>
            <strong>{{ message|safe }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
</div>

{% endif %}

templates/partials/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p>
    </div>
</footer>

templates/partials/nav-bar.html
{% load cart_tag %}
<!-- Top navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom fixed-top">
    <div class="container-fluid">
        <!-- toggler -->
        <button class="btn float-end" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button">
            <i class="bi bi-arrow-right-square-fill text-light fs-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvas"></i>
        </button>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                <li class="nav-item"><a class="nav-link {% if request.path == '/' %}active {% endif %}" href=" {% url 'base:home' %} "><i class="bi bi-house"></i> Home</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == '/about/' %}active {% endif %}" href=" {% url 'base:about' %} "><i class="bi bi-question-square"></i> About</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == '/contact/' %}active {% endif %}" href=" {% url 'base:contact' %} "><i class="bi bi-envelope-check"></i> Contact</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == '/faq/' %}active {% endif %}" href=" {% url 'base:faq' %} "><i class="bi bi-question-diamond"></i> Faq</a></li>
                <li class="nav-item"><a class="nav-link {% if request.path == '/pricing/' %}active {% endif %}" href=" {% url 'base:pricing' %} "><i class="bi bi-cash-coin"></i> Pricing</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path == '/products/all/' %}active {% endif %}" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="bi bi-shop"></i> Store</a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item {% if request.path == '/products/all/' %}active {% endif %} " href="{% url 'products:product_list' %}"><i class="fs-5 bi-grid"></i> All Products</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item {% if request.path == '/products/all/sale' %}active {% endif %}" href="#!"><i class="bi bi-bookmark-star"></i> On Sale</a>
                        <a class="dropdown-item {% if request.path == '/products/all/popular' %}active {% endif %}" href="#!"><i class="bi bi-heart"></i> Popular Items</a>
                        <a class="dropdown-item {% if request.path == '/products/all/new' %}active {% endif %}" href="#!"><i class="bi bi-clock"></i> New Arrivals</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item {% if request.path == '/products/categories/' %}active {% endif %}" href="#!"><i class="bi bi-boxes"></i> Categories</a>
                    </div>
                </li>

                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link btn btn-outline-light" href="{% url 'cart:cart-home' %}">
                        <i class="bi-cart-fill me-1"></i> Cart
                        <span class="badge badge-light">{{ request.user| cart_total }}</span>
                    </a>
                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

templates/partials/side-bar.html
<!-- Sidebar-->


<div class="offcanvas offcanvas-start w-25 bg-dark" tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-backdrop="false">
    <div class="offcanvas-header">
        <h6 class="offcanvas-title d-none d-sm-block fw-bolder fs-3 text-light" id="offcanvas"><i class="bi bi-columns-gap"></i> {{ site_name|upper }}</h6>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body px-0">
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
            {% if page_title == 'products' %}
            <li class="nav-item" style="cursor: pointer;">
                <div class="nav-link text-truncate text-warning" data-bs-toggle="modal" data-bs-target="#exampleModal">
                    <i class="bi bi-search"></i>
                    <span class="ms-1 d-none d-sm-inline">Search</span>
                </div>
            </li>

            {% endif %}
            <!---->
            {% if request.user.is_authenticated %}
            <li>
                <a href="#submenu1" data-bs-toggle="collapse" class="nav-link text-truncate">
                    <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
            </li>
            <li>
                <a href="#" class="nav-link text-truncate">
                    <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Orders</span></a>
            </li>

            <li>
                <a href="#" class="nav-link text-truncate">
                    <i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline">My Products</span></a>
            </li>
            <li>
                <a href="#" class="nav-link text-truncate">
                    <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">Customers</span> </a>
            </li>
            {% endif %}

            <li class="dropdown">
                <!---->
                {% if request.user == profile.user %}
                <!---->
                <a href="#" class="nav-link dropdown-toggle  text-truncate" id="settings" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-gear-fill"></i><span class="ms-1 d-none d-sm-inline">Edit</span>
                </a>

                <ul class="dropdown-menu text-small shadow" aria-labelledby="settings">
                    <li>
                        <a class="dropdown-item" href="{% url 'products:create_product' profile.slug %}">
                            <i class="bi bi-bag-plus-fill"></i> Create Product
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'users:user_update' profile.slug %}">
                            <i class="bi bi-person-lines-fill"></i> Edit Profile</a>
                    </li>
                    <!---->
                </ul>
                <!---->


            </li>
            {% endif %}
            <li class="dropdown">
                <a href="#" class="nav-link dropdown-toggle  text-truncate" id="account" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-briefcase"></i></i><span class="ms-1 d-none d-sm-inline">Account</span>
                </a>
                <!---->
                <ul class="dropdown-menu text-small shadow" aria-labelledby="account">
                    <!---->
                    {% if request.user.is_authenticated %}
                    <!---->

                    <li>
                        <a class="dropdown-item" href="{% url 'users:user_detail' request.user.profile.slug %}">
                            <i class="bi bi-person-circle"></i> Profile
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                            <i class="bi bi-box-arrow-right"></i> Logout
                        </a>
                    </li>
                    <!---->
                    {% else %}
                    <li>
                        <a class="dropdown-item" href="{% url 'accounts:login' %}">
                            <i class="bi bi-box-arrow-right"></i> Login
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'accounts:register' %}">
                            <i class="bi bi-pencil-square"></i> Register
                        </a>
                    </li>

                    <!---->
                    {% endif %}
                </ul>
            </li>
        </ul>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Filter Products</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="get" class="p2">
                <div class="modal-body">
                    <div class="form-floating mb-1">
                        <div class="fw-bolder text-dark">Name</div>
                        <input class="form-control mb-2" type="text" name="name" id="id_name">
                        <div class="fw-bolder text-dark">Min Price</div>
                        <input class="form-control mb-2" type="text" name="price_min" id="id_price_0">
                        <div class="fw-bolder text-dark">Max Price</div>
                        <input class="form-control mb-2" type="text" name="price_max" id="id_price_1">
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-sm btn-outline-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>