base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('about/', views.About.as_view(), name="about"),
    path('contact/', views.Contact.as_view(), name="contact"),
    path('faq/', views.Faq.as_view(), name="faq"),
    path('pricing/', views.Pricing.as_view(), name="pricing"),
    
]

cart/urls.py
  
from django.urls import path
from cart.views import add_to_cart, remove_from_cart, CartView, decreaseCart

app_name= 'cart'

urlpatterns = [
    
    path('cart/', CartView, name='cart-home'),
    path('cart/<slug>', add_to_cart, name='cart'),
    path('decrease-cart/<slug>', decreaseCart, name='decrease-cart'),
    path('remove/<slug>', remove_from_cart, name='remove-cart'),
]

products/urls.py
from django.urls import path
from . import views  

app_name = 'products'

urlpatterns = [
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'), 
    path('all/', views.ProductListView.as_view(), name='product_list'),
    path('create/product/<slug:slug>/', views.ProductCreateView.as_view(), name='create_product'),
    path('delete/product/<slug:slug>/', views.ProductDeleteView.as_view(), name='delete_product'),
    path('update/product/<slug:slug>/', views.ProductUpdateView.as_view(), name='update_product'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('timeline/<slug>/', views.UserDetailView.as_view(), name='user_detail'),
    path('all/', views.UserListView.as_view(), name='users'),
    path('update/profile/<slug>/', views.UserUpdateView.as_view(), name='user_update'),
    path('delete/profile/<slug>/', views.UserDeleteView.as_view(), name='user_delete'),
]

vstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User
from django.template.defaultfilters import slugify 
from django.utils.translation import gettext_lazy as _






class Category(models.Model):
    
    name = models.CharField(default='', max_length=50)
    slug = models.SlugField(unique=True, null=True)

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categorys")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Category_detail", kwargs={"slug": self.slug})


class Product(models.Model):

    user = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    #tags = models.ManyToManyField("index.Tag", related_name='products')
    name = models.CharField(default='', max_length=50)
    slug = models.SlugField(unique=True, null=True)
    description = models.TextField(blank=True)
    image = models.ImageField(default='products/default.png', upload_to='products')
    price = models.DecimalField(default=0.00, max_digits=15, decimal_places=2)
    sale_price = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)
    price_range_from = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)
    price_range_to = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=2)
    published = models.DateTimeField(auto_now=True, auto_now_add=False)
    views = models.PositiveIntegerField(default=0)
    unique = models.BooleanField(default=False)
    sale = models.BooleanField(default=False)
    special = models.BooleanField(default=False)
    fancy = models.BooleanField(default=False)
    popular = models.BooleanField(default=False)

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("products:product_detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs): # new
        if not self.slug:
            self.slug = slugify(self.user.username + self.name)
        return super().save(*args, **kwargs)

products/forms.py
from django import forms
from .models import Product


# Create your forms here.

class ProductForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = ("category", "name", "image", "description", "price",)

        

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        
        self.fields['category'].widget.attrs['class'] = 'form-control form-select'
        #self.fields['tags'].widget.attrs['class'] = 'form-control'
        self.fields['image'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['description'].widget.attrs['class'] = 'form-control mb-2'
        self.fields['price'].widget.attrs['class'] = 'form-control'

    #def save(self, commit=True):
    #    Product = super(ProductForm, self).save(commit=False)
    #    user.email = self.cleaned_data['email']
    #    if commit:
    #        user.save()
    #    return user

products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Product
from .forms import ProductForm
from django.urls import reverse_lazy
from django.contrib import messages
from .filters import ProductFilter
# Create your views here.


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = "create-product.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, f"{form.instance.name} has been successfully created.")
        return super(ProductCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = 'create-product'
        return context
    

class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = "update-product.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = 'update-product'
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        messages.success(self.request, f"{form.instance.name} has been successfully updated.")
        return super(ProductUpdateView, self).form_valid(form)

class ProductDeleteView(DeleteView):
    model = Product
    template_name = "confirm-delete-product.html"
    success_url = reverse_lazy('base:home')
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = 'confirm delete product'
        return context

    def form_valid(self, form):
        #form.instance.user = self.request.user
        messages.success(self.request, f"{form.instance.name} has been successfully Deleted.")
        return super(ProductDeleteView, self).form_valid(form)

class ProductListView(ListView):
    model = Product
    paginate_by = 20
    context_object_name = 'products'
    template_name = 'products.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ProductFilter(self.request.GET, queryset=self.get_queryset())
        context["page_title"] = 'products'
        return context
    
class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'product.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = 'product'
        return context
    
    
    

products/templates/confirm-delete-product.html
{% extends 'base.html' %}
<!--#############-->

{% block content %}
<div class="container-fluid" style="margin-top:100px;margin-bottom:100px">
    <form action="" method="post">
        {% csrf_token %} {{ form }}
        <h4 class="text-danger mb-5">Are you sure you want to delete {{object}}?? </h4>
        <button class="btn btn-sm btn-outline-danger mb-2" type="submit">Yes Iam Sure</button>
        <a class="btn btn-sm btn-outline-primary mb-2" href=" {{object.get_absolute_url}} ">No Go Back</a>
    </form>
</div>
{% endblock content %}

products/templates/create-product.html
{% extends 'base.html' %}
<!--#############-->

{% block content %}
<div class="container mb-5" style="margin-top: 100px;">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!---->
        {% for field in form %}
        <div class="form-floating mb-3">
            <div class="fw-bolder">{{field.label}}</div>
            <!---->
            {{ field }}
        </div>
        <!---->
        {% endfor %}
        <button class="btn btn-sm btn-outline-primary my-5" type="submit">Create</button>
    </form>
</div>
{% endblock content %}

products/templates/product.html
{% extends 'base.html' %}
<!--#############-->

{% block content %}

<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image.url }}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">SKU: BST-498</div>
                <h1 class="display-5 fw-bolder">{{ product.name|title }}</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through">${{ product.price }}</span>
                    <span>${{ product.sale_price }}</span>
                </div>
                <p>{{ product.description|capfirst }}</p>

                {% if product.user == request.user %}
                <a class="btn btn-sm btn-outline-success" href="{% url 'products:update_product' product.slug %}">Update product</a>
                <a class="btn btn-sm btn-outline-danger" href="{% url 'products:delete_product' product.slug %}">Delete product</a>
                <!---->
                {% else %}
                <a class="btn btn-sm btn-outline-primary mb-2" href="{% url 'users:user_detail' product.user.profile.slug %}">{{ product.user.username|title }}</a>

                <div class="d-flex">
                    <a href="{% url 'cart:cart' object.slug %}" class="btn btn-md btn-outline-primary text-uppercase">
                        <i class="bi-cart-fill me-1"></i> Add to cart
                    </a>

                </div>
                {% endif %}

            </div>
        </div>
    </div>
</section>
<!-- Related items section-->
<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Related products</h2>
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Fancy Product</h5>
                            <!-- Product price-->
                            $40.00 - $80.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Sale badge-->
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Special Item</h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            <span class="text-muted text-decoration-line-through">$20.00</span> $18.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Sale badge-->
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Sale Item</h5>
                            <!-- Product price-->
                            <span class="text-muted text-decoration-line-through">$50.00</span> $25.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">Popular Item</h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            $40.00
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

products/templates/products.html
{% extends 'base.html' %}
<!--#############-->

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row justify-content-center">

            {% for p in filter.qs %} {% if p.unique %}
            <div class="col-lg-3 col-md-6 col-sm-12 mb-5 mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src=" {{ p.image.url }} " alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder"> {{ p.name }} </h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            ${{ p.price }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href=" {{ p.get_absolute_url }} ">View Options</a></div>
                    </div>
                </div>
            </div>
            {% elif p.fancy %}
            <!-- Fancy Product -->
            <div class="col-lg-3 col-md-6 col-sm-12 mb-5 mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src=" {{ p.image.url }} " alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ p.name }} </h5>
                            <!-- Product price-->
                            ${{ p.price_range_from }} - ${{ p.price_range_to }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href=" {{ p.get_absolute_url }} ">View</a></div>
                    </div>
                </div>
            </div>
            {% elif p.special %}
            <!-- Special Product -->
            <div class="col-lg-3 col-md-6 col-sm-12 mb-5 mb-5">
                <div class="card h-100">
                    <!-- Sale badge-->
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    <!-- Product image-->
                    <img class="card-img-top" src=" {{ p.image.url }} " alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ p.name }} </h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            <span class="text-muted text-decoration-line-through">${{ p.price }} </span> ${{ p.sale_price }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href=" {{ p.get_absolute_url }} ">View</a></div>
                    </div>
                </div>
            </div>
            {% elif p.sale %}
            <!-- Sale Product -->
            <div class="col-lg-3 col-md-6 col-sm-12 mb-5 mb-5">
                <div class="card h-100">
                    <!-- Sale badge-->
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                    <!-- Product image-->
                    <img class="card-img-top" src=" {{ p.image.url }} " alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ p.name }} </h5>
                            <!-- Product price-->
                            <span class="text-muted text-decoration-line-through">${{ p.price }} </span> ${{ p.sale_price }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href=" {{ p.get_absolute_url }} ">View</a></div>
                    </div>
                </div>
            </div>
            {% else %}
            <!-- Popular Product -->
            <div class="col-lg-3 col-md-6 col-sm-12 mb-5 mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src=" {{ p.image.url }} " alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ p.name }} </h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            ${{ p.price }}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href=" {{ p.get_absolute_url }} ">View</a></div>
                    </div>
                </div>
            </div>

            {% endif %} {% endfor %}


        </div>
    </div>
</section>
<section>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <!---->
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">First</a>

            </li>
            <li class="page-item">

                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
            <!---->
            {% endif %}
            <li class="page-item disabled"><a class="page-link" href="#">Page</a></li>
            <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
            <li class="page-item disabled"><a class="page-link" href="#">Of</a></li>
            <li class="page-item"><a class="page-link" href="#">{{ page_obj.paginator.num_pages }}</a></li>
            <!---->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            <!---->
            {% endif %}
        </ul>
    </nav>

</section>
{% endblock content %}

products/templates/update-product.html
{% extends 'base.html' %}
<!--#############-->

{% block content %}

<div class="container mb-5" style="margin-top: 100px;">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <!---->
        {% for field in form %}
        <div class="form-floating mb-3">
            <div class="fw-bolder">{{field.label}}</div>
            <!---->
            {{ field }}
        </div>
        <!---->
        {% endfor %}
        <button class="btn btn-sm btn-outline-primary" type="submit">Update</button>
    </form>
</div>

{% endblock content %}